# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "CREDENTIALS" ("USERNAME" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
create unique index "INDEX_NAME" on "CREDENTIALS" ("USERNAME");
create table "SETTINGS" ("SETTINGS_KEY" VARCHAR NOT NULL,"SETTINGS_VALUE" INTEGER NOT NULL,"SETTINGS_CREDS_ID" INTEGER NOT NULL,"SETTINGS_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
alter table "SETTINGS" add constraint "FK_CRED" foreign key("SETTINGS_CREDS_ID") references "CREDENTIALS"("ID") on update CASCADE on delete CASCADE;

# --- !Downs

alter table "SETTINGS" drop constraint "FK_CRED";
drop table "CREDENTIALS";
drop table "SETTINGS";

